/*
 * This file was automatically generated by oml2-scaffold V2.11.0rc.3-6bff-dirty
 * for generator version 1.0.0.
 * Please edit to suit your needs; the run() function should contain application code.
 */

#include <unistd.h> /* Needed for sleep(3) in run() */
#include <signal.h>
#include <string.h>
#include <popt.h>
#include <oml2/omlc.h>
#include <stdlib.h>

#define USE_OPTS /* Include command line parsing code*/
#include "generator_popt.h"

#define OML_FROM_MAIN /* Define storage for some global variables; #define this in only one file */
#include "generator_oml.h"

#include "config.h"

int loop = 1;

static void
sighandler (int signum) {
  switch (signum) {
    case SIGINT:
      /* Terminate on SIGINT */
      loop = 0;
      break;

  }
}

char * readFile(FILE *file) //read string from file
{
    if( file == NULL )
    {   
        return NULL;
    }    

    fseek(file, 0, SEEK_END );
    int size = ftell(file);
    rewind(file);
    char * string = calloc(size+1,1);
    fread(string,1,size,file);
    return string;
}


/* Do application-specific work here.
 */

void
run(opts_t *opts, oml_mps_t *oml_mps)
{
  long val = 1;
  struct sigaction sa;
  int i;
  FILE *fp;
  int rx = 10;
  char *string;

  bzero(&sa, sizeof(struct sigaction));
  sa.sa_handler = sighandler;
  sigaction(SIGINT, &sa, NULL);
  
  for(i=0;i<100; i++)
   {
     system("ifconfig eth0 | grep bytes | awk '{print $2}' | cut -c 1-6 --complement > traffic.txt");
     fp = fopen("traffic.txt","r");    // caculating total traffic
	 string = readFile(fp);
	 rx = atoi(string);
     fclose(fp);
     oml_inject_sensor(oml_mps->sensor,rx);
   }

  do {
    /* The oml_inject_MPNAME() helpers are defined in generator_oml.h*/
    if(oml_inject_sensor(oml_mps->sensor, ((int32_t)-val)) != 0) {
      logwarn("Failed to inject data into MP 'sensor'\n");
    }

    val += 2;
    sleep(1);
  } while (loop);
}

int
main(int argc, const char *argv[])
{
  int c, i, ret;

  /* Reconstruct command line */
  size_t cmdline_len = 0;
  for(i = 0; i < argc; i++) {
    cmdline_len += strlen(argv[i]) + 1;
  }
  char *cmdline = oml_malloc(cmdline_len);
  cmdline[0] = '\0';
  for(i = 0; i < argc; i++) {
    strncat(cmdline, argv[i], cmdline_len);
    cmdline_len -= strlen(argv[i]);
    strncat(cmdline, " ", cmdline_len);
    cmdline_len--;
  }

  /* Initialize OML */
  if((ret = omlc_init("generator", &argc, argv, NULL)) < 0) {
    logerror("Could not initialise OML\n");
    return -1;
  }

  /* Parse command line arguments */
  poptContext optCon = poptGetContext(NULL, argc, argv, options, 0); /* options is defined in generator_popt.h */
  while ((c = poptGetNextOpt(optCon)) > 0) {}

  /* Initialise measurement points and start OML */
  oml_register_mps(); /* Defined in generator_oml.h */
  if(omlc_start()) {
    logerror("Could not start OML\n");
    return -1;
  }

  /* Inject some metadata about this application */
  OmlValueU v;
  omlc_zero(v);
  omlc_set_string(v, PACKAGE_NAME);
  omlc_inject_metadata(NULL, "appname", &v, OML_STRING_VALUE, NULL);

  omlc_set_string(v, PACKAGE_VERSION);
  omlc_inject_metadata(NULL, "version", &v, OML_STRING_VALUE, NULL);

  omlc_set_string(v, cmdline);
  omlc_inject_metadata(NULL, "cmdline", &v, OML_STRING_VALUE, NULL);
  omlc_reset_string(v);
  oml_free(cmdline);

  /* Inject measurements */
  run(g_opts, g_oml_mps_generator); /* Do some work and injections, see above */

  omlc_close();

  return 0;
}

/*
 Local Variables:
 mode: C
 tab-width: 2
 indent-tabs-mode: nil
 End:
 vim: sw=2:sts=2:expandtab
*/
