/*
 * This file was automatically generated by oml2-scaffold V2.11.0rc.3-6bff-dirty
 * for generator version 1.0.0.
 * Please do not edit.
 */

#ifndef GENERATOR_OPTS_H
#define GENERATOR_OPTS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  char* dpid;

} opts_t;

#ifndef USE_OPTS

opts_t* g_opts;

#else

static opts_t g_opts_storage = {""};
opts_t* g_opts = &g_opts_storage;

/* Only the file containing the main() function should come through here */

#include <popt.h>

struct poptOption options[] = {
  POPT_AUTOHELP
  { "dpid", 'd', POPT_ARG_STRING, &g_opts_storage.dpid, 'l', "Create periodic result"},

  { NULL, 0, 0, NULL, 0 }
};

#endif /* USE_OPTS */

#ifdef __cplusplus
}
#endif

#endif /* GENERATOR_OPTS_H */
